package com.travel.meomulkyung.itinerary.service;

import com.travel.meomulkyung.itinerary.domain.*;
import com.travel.meomulkyung.itinerary.dto.*;
import com.travel.meomulkyung.itinerary.external.*;
import com.travel.meomulkyung.itinerary.repository.*;
import com.travel.meomulkyung.region.domain.Region;
import com.travel.meomulkyung.region.repository.RegionRepository;
import com.travel.meomulkyung.user.domain.User;
import com.travel.meomulkyung.user.repository.UserRepository;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;

import java.time.Clock;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

@Service
@RequiredArgsConstructor
public class ItineraryService {
 private final ItineraryRepository itineraries; private final ItineraryItemRepository items; private final RegionRepository regions; private final UserRepository users; private final CompletedTripRepository completed; private final UserStampRepository stamps; private final TourPlaceProvider places; private final FestivalProvider festivals; private final WeatherProvider weather; private final Clock clock;
 @Transactional public ItineraryResponses.Itinerary create(Long userId, ItineraryRequests.Create request) { if (request.duplicate()) throw error(HttpStatus.BAD_REQUEST,"INVALID_PREFERENCE_TAGS","취향 태그는 중복될 수 없습니다."); Region region=regions.findById(request.regionId()).orElseThrow(()->error(HttpStatus.NOT_FOUND,"REGION_NOT_FOUND","지역을 찾을 수 없습니다.")); User user=users.findById(userId).orElseThrow(()->error(HttpStatus.UNAUTHORIZED,"ACCESS_TOKEN_INVALID","인증 사용자를 찾을 수 없습니다.")); Itinerary itinerary=new Itinerary(user,region,request.startDate(),request.nights(),request.preferenceTags(),request.companionType()); itineraries.save(itinerary); return response(itinerary,generate(itinerary,false)); }
 @Transactional public ItineraryResponses.Itinerary get(Long userId,Long id){return response(owner(userId,id),List.of());}
 @Transactional public ItineraryResponses.Replacement replace(Long uid,Long iid,Long itemId,ItineraryRequests.Replace request){Itinerary itinerary=owner(uid,iid);if(itinerary.getStatus()==ItineraryStatus.COMPLETED)throw error(HttpStatus.CONFLICT,"ITINERARY_ALREADY_COMPLETED","완료된 일정은 변경할 수 없습니다.");ItineraryItem old=itinerary.getItems().stream().filter(item->item.getId().equals(itemId)).findFirst().orElseThrow(()->error(HttpStatus.NOT_FOUND,"ITINERARY_ITEM_NOT_FOUND","일정 항목을 찾을 수 없습니다."));if(!old.isReplaceable())throw error(HttpStatus.CONFLICT,"ITEM_NOT_REPLACEABLE","교체할 수 없는 항목입니다.");Set<Long> excluded=itinerary.getItems().stream().map(ItineraryItem::getContentId).filter(Objects::nonNull).collect(Collectors.toSet());TourPlaceProvider.Place place=places.findPlaces(itinerary.getRegion()).stream().filter(candidate->candidate.type()==old.getItemType()).filter(candidate->!excluded.contains(candidate.contentId())).findFirst().orElseThrow(()->error(HttpStatus.UNPROCESSABLE_ENTITY,"NOT_ENOUGH_PLACES","대체 후보가 부족합니다."));old.replace(place.contentId());itinerary.incrementGenerationVersion();return new ItineraryResponses.Replacement(itinerary.getId(),old.getId(),item(old,place),itinerary.getGenerationVersion());}
 @Transactional public ItineraryResponses.Itinerary regenerate(Long uid,Long id,ItineraryRequests.Replace request){Itinerary itinerary=owner(uid,id);if(itinerary.getStatus()==ItineraryStatus.COMPLETED)throw error(HttpStatus.CONFLICT,"ITINERARY_ALREADY_COMPLETED","완료된 일정은 재생성할 수 없습니다.");List<ItineraryResponses.Warning> warnings=generate(itinerary,request.excludePreviouslyRecommended());itinerary.incrementGenerationVersion();return response(itinerary,warnings);}
 @Transactional public ItineraryResponses.Bookmark bookmark(Long uid,Long id){Itinerary itinerary=owner(uid,id);itinerary.bookmark();return new ItineraryResponses.Bookmark(itinerary.getId(),true,itinerary.getBookmarkedAt());}
 @Transactional public void unbookmark(Long uid,Long id){owner(uid,id).unbookmark();}
 @Transactional public ItineraryResponses.Completion complete(Long uid,Long id,ItineraryRequests.Completion request){Itinerary itinerary=owner(uid,id);if(completed.existsByItineraryId(id)||itinerary.getStatus()==ItineraryStatus.COMPLETED)throw error(HttpStatus.CONFLICT,"ITINERARY_ALREADY_COMPLETED","이미 완료된 일정입니다.");itinerary.complete();CompletedTrip trip=completed.save(new CompletedTrip(itinerary,request.stayHours(),request.partySize(),request.totalSpent()));Optional<UserStamp> existing=stamps.findByUserIdAndRegionId(uid,itinerary.getRegion().getId());UserStamp stamp=existing.orElseGet(()->stamps.save(new UserStamp(itinerary.getUser(),itinerary.getRegion())));if(existing.isPresent())stamp.visit();return new ItineraryResponses.Completion(trip.getId(),id,region(itinerary.getRegion()),request.stayHours(),request.partySize(),request.totalSpent(),new ItineraryResponses.Stamp(true,existing.isEmpty(),itinerary.getRegion().getId(),itinerary.getRegion().getName(),stamp.getVisitCount()),new ItineraryResponses.Contribution(null,"PENDING_POLICY",null),trip.getCompletedAt());}
 public ItineraryResponses.WeatherDays weather(Long uid,Long id){Itinerary itinerary=owner(uid,id);LocalDate now=LocalDate.now(clock);return new ItineraryResponses.WeatherDays(days(itinerary).map(date->{if(date.isAfter(now.plusDays(10)))return new ItineraryResponses.WeatherDay(date,false,null,null);WeatherProvider.Weather value=weather.weather(itinerary.getRegion(),date);return new ItineraryResponses.WeatherDay(date,value.available(),value.icon(),value.temperature());}).toList());}
 private List<ItineraryResponses.Warning> generate(Itinerary itinerary,boolean exclude){List<TourPlaceProvider.Place> candidates=places.findPlaces(itinerary.getRegion());int days=itinerary.getNights()+1;if(candidates.size()<days)throw error(HttpStatus.UNPROCESSABLE_ENTITY,"NOT_ENOUGH_PLACES","일정을 구성할 장소가 부족합니다.");List<FestivalProvider.Festival> matched;List<ItineraryResponses.Warning> warnings=List.of();try{matched=festivals.findFestivals(itinerary.getRegion(),itinerary.getStartDate(),itinerary.getEndDate()).stream().filter(festival->overlaps(itinerary,festival)).toList();}catch(RuntimeException exception){matched=List.of();warnings=List.of(new ItineraryResponses.Warning("FESTIVAL_DATA_UNAVAILABLE","축제 정보를 일정에 반영하지 못했습니다."));}List<ItineraryItem> next=new ArrayList<>();int candidateIndex=0;for(int day=1;day<=days;day++){int sequence=1;if(day==1)next.add(new ItineraryItem(itinerary,day,sequence++,ItineraryItemType.ARRIVAL,null,"ARRIVAL"));TourPlaceProvider.Place place=candidates.get(candidateIndex++%candidates.size());next.add(new ItineraryItem(itinerary,day,sequence++,place.type(),place.contentId(),null));for(FestivalProvider.Festival festival:matched){if(festivalDay(itinerary,festival)==day)next.add(new ItineraryItem(itinerary,day,sequence++,festival.contentId(),festival.title(),festival.imageUrl(),festival.address(),festival.startDate(),festival.endDate()));}if(day<=itinerary.getNights())next.add(new ItineraryItem(itinerary,day,sequence++,ItineraryItemType.REST,null,"REST"));if(day==days)next.add(new ItineraryItem(itinerary,day,sequence,ItineraryItemType.DEPARTURE,null,"DEPARTURE"));}itinerary.replaceItems(next);return warnings;}
 private boolean overlaps(Itinerary itinerary,FestivalProvider.Festival festival){return festival.startDate()!=null&&festival.endDate()!=null&&!festival.startDate().isAfter(itinerary.getEndDate())&&!festival.endDate().isBefore(itinerary.getStartDate());}
 private int festivalDay(Itinerary itinerary,FestivalProvider.Festival festival){LocalDate date=festival.startDate().isBefore(itinerary.getStartDate())?itinerary.getStartDate():festival.startDate();return (int)ChronoUnit.DAYS.between(itinerary.getStartDate(),date)+1;}
 private Itinerary owner(Long uid,Long id){Itinerary itinerary=itineraries.findDetailById(id).orElseThrow(()->error(HttpStatus.NOT_FOUND,"ITINERARY_NOT_FOUND","일정을 찾을 수 없습니다."));if(!itinerary.getUser().getId().equals(uid))throw error(HttpStatus.FORBIDDEN,"ITINERARY_ACCESS_DENIED","일정 접근 권한이 없습니다.");return itinerary;}
 private ItineraryResponses.Itinerary response(Itinerary itinerary,List<ItineraryResponses.Warning> warnings){return new ItineraryResponses.Itinerary(itinerary.getId(),itinerary.getStatus().name(),itinerary.isBookmarked(),region(itinerary.getRegion()),itinerary.getTitle(),itinerary.getStartDate(),itinerary.getEndDate(),itinerary.getNights(),itinerary.getGenerationVersion(),days(itinerary).map(date->new ItineraryResponses.Day((int)ChronoUnit.DAYS.between(itinerary.getStartDate(),date)+1,date,weather(itinerary.getRegion(),date),itinerary.getItems().stream().filter(item->item.getDayNumber()==(int)ChronoUnit.DAYS.between(itinerary.getStartDate(),date)+1).map(item->item(item,null)).toList())).toList(),warnings);}
 private ItineraryResponses.Weather weather(Region region,LocalDate date){WeatherProvider.Weather value=weather.weather(region,date);return new ItineraryResponses.Weather(value.available(),value.icon(),value.minimumTemperature(),value.maximumTemperature());} private Stream<LocalDate> days(Itinerary itinerary){return itinerary.getStartDate().datesUntil(itinerary.getEndDate().plusDays(1));} private ItineraryResponses.Region region(Region region){return new ItineraryResponses.Region(region.getId(),region.getName());} private ItineraryResponses.Item item(ItineraryItem item,TourPlaceProvider.Place place){String title=place!=null?place.title():item.getCustomTitle()!=null?item.getCustomTitle():"PLACE "+item.getContentId();String imageUrl=place!=null?place.imageUrl():item.getImageUrl();String address=place!=null?place.address():item.getAddress();return new ItineraryResponses.Item(item.getId(),item.getSequence(),item.getItemType().name(),title,item.getItemType()==ItineraryItemType.FESTIVAL?null:item.getContentId(),item.getItemType()==ItineraryItemType.FESTIVAL?item.getContentId():null,imageUrl,address,item.getEventStartDate(),item.getEventEndDate(),null,item.isReplaceable());} private ItineraryException error(HttpStatus status,String code,String message){return new ItineraryException(status,code,message);}
}
